### ISSUE TITLE
Bug when starting up v1.13.0

### ISSUE THREAD

**Issue by brands-d** [brands-d/kMap#45]
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/user/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/git/kMap/kmap/__main__.py", line 2, in <module>
    from kmap.kMap import kMap
  File "/home/user/git/kMap/kmap/kMap.py", line 93
    if (path := config.get_key('paths', 'matplotlib')) != 'None':

**Comment by brands-d** [comment]
Not a bug but because I included syntax only available in 3.8.x (walrus operator) older versions don't work anymore. I removed the syntax in 1.13.1 (9c605d3). Python 3.7 should work again, older versions were not officially supported before either.
